### PR TITLE
Fix various memory leaks

### LINKED ISSUE #362: Memory leaks in all test running "make check"
I compiled i3status, without any apparent issues, when I run "make check", i get the following output. I am using the last commit 5aec4a5da32e9a1fad1a89f17b10d676d4312895 from git repository.

Can someone try to reproduce it to see if it's something about my build, or it is a real issue ?
Thanks

 ```
=====================================
   i3status 2.13: ./test-suite.log
=====================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: travis/run-tests.pl
=========================


=================================================================
==7423==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f4fdfff3330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f4fdfef388e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f4fdfef522f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4fdfff3330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f4fdfef2d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f4fdfef522f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '001-battery'… Crash!

=================================================================
==7430==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f4477567330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f447746788e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f447746922f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4477567330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f4477466d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f447746922f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '007-cpu-usage-degraded-threshold-format'… Crash!

=================================================================
==7439==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7fbb80db7330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fbb80cb788e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7fbb80cb922f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fbb80db7330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fbb80cb6d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7fbb80cb922f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '003-path-exists'… Crash!

=================================================================
==7446==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f23ff58a330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f23ff48a88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f23ff48c22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f23ff58a330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f23ff489d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f23ff48c22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '019-battery-capacity'… Crash!

=================================================================
==7456==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f910be62330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f910bd6288e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f910bd6422f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f910be62330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f910bd61d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f910bd6422f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '015-battery-capacity'… Crash!

=================================================================
==7461==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7ff669cd8330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7ff669bd888e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7ff669bda22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7ff669cd8330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7ff669bd7d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7ff669bda22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '018-battery-capacity'… Crash!

=================================================================
==7466==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f07a4daa330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f07a4caa88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f07a4cac22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f07a4daa330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f07a4ca9d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f07a4cac22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '009-disk-low-threshold-format'… Crash!
i3status: provided CPU number '10' above detected number of CPU 4

=================================================================
==7474==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f1fcd40b330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f1fcd30b88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f1fcd30d22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f1fcd40b330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f1fcd30ad5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f1fcd30d22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '022-cpu-usage-tenth-cpu'… Crash!

=================================================================
==7484==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7fe2aa337330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fe2aa23788e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7fe2aa23922f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fe2aa337330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fe2aa236d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7fe2aa23922f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '011-cpu-usage'… Crash!

=================================================================
==7491==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f4350e0e330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f4350d0e88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f4350d1022f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4350e0e330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f4350d0dd5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f4350d1022f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '002-cpu-temp'… Crash!

=================================================================
==7496==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f646956c330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f646946c88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f646946e22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f646956c330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f646946bd5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f646946e22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '021-battery-second'… Crash!
i3status: Cannot read CPU usage

=================================================================
==7501==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f0ec669a330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f0ec659a88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f0ec659c22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f0ec669a330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f0ec6599d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f0ec659c22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '012-cpu-usage-error'… Crash!

=================================================================
==7506==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f6a016330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f8f69f1688e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f8f69f1822f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f6a016330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f8f69f15d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f8f69f1822f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '008-load-max-threshold-format'… Crash!

=================================================================
==7513==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7fc343d83330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fc343c8388e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7fc343c8522f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fc343d83330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fc343c82d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7fc343c8522f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '016-ethernet-down'… Crash!

=================================================================
==7523==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f6f211be330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f6f210be88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f6f210c022f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f6f211be330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f6f210bdd5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f6f210c022f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '025-file-contents'… Crash!
i3status: provided CPU number cannot be parsed
=================================================================
==7528==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000319a at pc 0x561cbbf17dbd bp 0x7ffcf0b2d050 sp 0x7ffcf0b2d048
READ of size 1 at 0x60200000319a thread T0
    #0 0x561cbbf17dbc in print_cpu_usage (/home/guiu/source/i3status/build/i3status+0x28dbc)
    #1 0x561cbbf0ee3c in main (/home/guiu/source/i3status/build/i3status+0x1fe3c)
    #2 0x7f4941eb209a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #3 0x561cbbeffdf9 in _start (/home/guiu/source/i3status/build/i3status+0x10df9)

0x60200000319a is located 0 bytes to the right of 10-byte region [0x602000003190,0x60200000319a)
allocated by thread T0 here:
    #0 0x7f49427d1810 in strdup (/lib/x86_64-linux-gnu/libasan.so.5+0x3a810)
    #1 0x7f494278d4ad in cfg_setopt (/lib/x86_64-linux-gnu/libconfuse.so.2+0x54ad)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/guiu/source/i3status/build/i3status+0x28dbc) in print_cpu_usage
Shadow bytes around the buggy address:
  0x0c047fff85e0: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff85f0: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff8600: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff8610: fa fa 00 fa fa fa 00 fa fa fa 05 fa fa fa 00 fa
  0x0c047fff8620: fa fa 00 fa fa fa 00 02 fa fa 00 fa fa fa 00 fa
=>0x0c047fff8630: fa fa 00[02]fa fa 00 fa fa fa fa fa fa fa fa fa
  0x0c047fff8640: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8650: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8660: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8670: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7528==ABORTING
Testing test case '024-cpu-usage-invalid-cpu'… Crash!

=================================================================
==7531==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f1ed2a50330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f1ed295088e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f1ed295222f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f1ed2a50330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f1ed294fd5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f1ed295222f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '017-wireless-down'… Crash!

=================================================================
==7536==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7ff23a82e330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7ff23a72e88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7ff23a73022f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7ff23a82e330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7ff23a72dd5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7ff23a73022f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '005-cpu-temp-max-threshold-format'… Crash!

=================================================================
==7541==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7fa2e0eff330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fa2e0dff88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7fa2e0e0122f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fa2e0eff330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fa2e0dfed5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7fa2e0e0122f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '006-cpu-usage-max-threshold-format'… Crash!

=================================================================
==7546==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7fc6ff0fd330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fc6feffd88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7fc6fefff22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fc6ff0fd330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fc6feffcd5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7fc6fefff22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '004-run-watch'… Crash!
i3status: Cannot read CPU usage

=================================================================
==7551==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7feaa5665330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7feaa556588e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7feaa556722f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7feaa5665330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7feaa5564d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7feaa556722f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '013-cpu-usage-error'… Crash!

=================================================================
==7562==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7fd5956aa330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fd5955aa88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7fd5955ac22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fd5956aa330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fd5955a9d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7fd5955ac22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '023-battery-not-charging'… Crash!

=================================================================
==7573==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7f029b17a330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f029b07a88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7f029b07c22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f029b17a330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f029b079d5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7f029b07c22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '014-battery-capacity'… Crash!

=================================================================
==7581==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x7fc3b6a9b330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fc3b699b88e in yajl_gen_alloc (/lib/x86_64-linux-gnu/libyajl.so.2+0x588e)
    #2 0x7fc3b699d22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fc3b6a9b330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fc3b699ad5e  (/lib/x86_64-linux-gnu/libyajl.so.2+0x4d5e)
    #2 0x7fc3b699d22f  (/lib/x86_64-linux-gnu/libyajl.so.2+0x722f)

SUMMARY: AddressSanitizer: 608 byte(s) leaked in 2 allocation(s).
Testing test case '010-cpu-usage'… Crash!
FAIL travis/run-tests.pl (exit status: 1)
```

### PR DESCRIPTION
**Pull request by orestisfl**
Fixes #362

### CODE REVIEW

**Comment by Airblader** [comment]
Would this allow us to enable sanitizers on Travis again?

**Comment by orestisfl** [comment]
Let me see.

On my system there is still a pulseaudio-related memleak which I believe is not our issue

**Comment by orestisfl** [comment]
Ok, it passes: https://travis-ci.org/github/i3/i3status/builds/681918649 let me re-introduce a leak to see if it catches it

**Comment by orestisfl** [comment]
It does: https://travis-ci.org/github/i3/i3status/builds/681919573

Nice

**Pull request merged**
