### PR TITLE
Several OS X compatibility changes, mainly for volume.

### PR DESCRIPTION
**Pull request by afh**
# Please Do Not Merge (Yet)

I may have found another (better?) way to access volume information on Mac OS X and therefore would like to put this pull request on hold while I research another approach.

### CODE REVIEW

**Comment by Airblader** [comment]
@afh Are you still working on this?

**Comment by afh** [comment]
Yes, I recently started working on this again.

In my workspace I've added support to retrieve the cpu temperature using [IOKit](https://developer.apple.com/library/mac/documentation/DeviceDrivers/Conceptual/IOKitFundamentals/Introduction/Introduction.html#//apple_ref/doc/uid/TP0000011-CH204-TPXREF101).

Using IOKit it might also be possible to retrieve the current volume.
I find the IOKit API a bit add odd and have yet to understand how to use it properly in addition to understanding the I/O device tree accessible via [ioreg(8)](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/ioreg.8.html).

**Comment by Airblader** [comment]
I'm going to close this now. Please open the PR once you continued working on this.

**Comment by afh** [comment]
Good call I'm not sure when I find time to continue working on this.

**Pull request closed without merging**
