### PR TITLE
Forgotten wakeup call from USR1 handler

### LINKED ISSUE #93: i3status 2.10 doesn't refresh when sent SIGUSR1
As the title says, the refresh doesn't work anymore for me. I'm using the Ubuntu wily and the stable repo mentioned on i3wm.org. But I can also reproduce the bug with a version I built from source.

How can I go about debugging this?

### PR DESCRIPTION
**Pull request by rpls**
Fixes #93 

I'm not a pthread expert. Is this the right way to do it? It fixed the issue for me.

### CODE REVIEW

**Comment by Watcom** [comment]
I'm not a pthread expert either, but quoting from the manpage:
> "It is not safe to use the pthread_cond_signal() function in a signal handler that is invoked asynchronously. Even if it were safe, there would still be a race between the test of the Boolean pthread_cond_wait() that could not be efficiently eliminated.

>  Mutexes and condition variables are thus not suitable for releasing a waiting thread by signaling from code running in a signal handler."

That being said, I don't know of any alternative solution. Of course, this is only an issue when (and if) you actually use USR1.

**Comment by rpls** [comment]
True. I did use the broadcast method though, don't know how much of a difference it makes. The restriction doesn't mention broadcast, but I guess the second paragraph kind of includes it too. Anyway, why was `nanosleep` removed? Doesn't this work with the PulseAudio patch?

**Comment by Watcom** [comment]
The change from `nanosleep` was so PulseAudio events could wake up the main thread (i.e. on volume changes).

**Comment by stapelberg** [comment]
Sounds to me like we should find a better solution, then. Maybe we can make use of signalfd in some way?

**Comment by Watcom** [comment]
I think `signalfd` is Linux-specific, though.

Perhaps the simplest way is to go back to using `nanosleep()` and then use `pthread_kill()` to send USR1 to the main thread from `pulse.c`, dropping the condition variable altogether. I haven't tried this but in theory it should work.

I see [other solutions](http://osiris.978.org/~alex/safesignalhandling.html), but all of them seem to add more complexity.

**Comment by stapelberg** [comment]
Going back to `nanosleep` as you suggested sounds good. Can you send a PR for that please?

**Pull request merged**
