### PR TITLE
Read multiple batteries on DragonFly BSD.

### PR DESCRIPTION
**Pull request by oyvinht**
Using ACPI to read individual battery information instead of just the
accumulations that sysctl provide.

Like for OpenBSD, it requires the system dependency sys/fcntl.h.

No other dependencies added or changed.

### CODE REVIEW

**Comment by Airblader** [comment]
I can't speak for whether it is correct, but since it affects only DragonFly, I'll rely on your expertise. However, could you please squash the commits? Thanks and sorry for the wait!

**Comment by oyvinht** [comment]
Sure, no problem. I have squashed together all commits since fork now.

I can't make any guarantees for stability - as I have only tested it myself - but it has been fault free here on a regularly updated system (DragonFlyBSD master branch) for the last three-four months.

**Comment by Airblader** [comment]
Thanks! I'll merge this after the i3status release. I do think it'd be good to have it run through some testing rather than instantly releasing it. :-)

**Comment by oyvinht** [comment]
Yes, it (as always) definitively is.

**Comment by Airblader** [comment]
I lost track of this a bit, I apologize. But let's go with it now. Thanks for the PR!

**Pull request merged**
