### PR TITLE
Fixes https://github.com/i3/i3status/issues/276

### PR DESCRIPTION
**Pull request by su8**

### CODE REVIEW

**Comment by Airblader** [comment]
Why is this an improvement? It requires more code and more explicit handling of the encoding. What's wrong with cat?

**Comment by su8** [comment]
`cat foo`, there is no check whether this command succeeded or not.

The improvement is that we use file handles instead spawning a new process and check whether the file exists, if not simply **die** with pre-defined message.

**Comment by su8** [comment]
If shorter version is required, then check the cat return value 

```perl

die "There is no @_/expected_output.txt" unless $? == cats_return_value_equals_ok

```

**Comment by Airblader** [comment]
I appreciate you filing the PR, but I think I'll close it for now because I don't think the tradeoff is very good here. Thanks for understanding!

**Pull request closed without merging**
