### PR TITLE
Provide format_above_threshold/format_below_threshold options

### PR DESCRIPTION
**Pull request by mihaicmn**
See #177 for more details. Any feedback is appreciated.

### CODE REVIEW

**Comment by Airblader** [comment]
I'd like if we can take this opportunity to add tests for this, given that we just introduced some infrastructure for that.

**Comment by mihaicmn** [comment]
Agreed! Should I use this PR or create a new one?

**Comment by Airblader** [comment]
Change and tests go together, so this PR (which I haven't looked at yet).

**Comment by eplanet** [comment]
@mihaicmn while it's great that you worked on this, you **should** have mentioned it in the issue thread, since somebody else can be working in parallel on the same issue without knowing it's a waste of time…

**Comment by mihaicmn** [comment]
@eplanet You are right, I apologize for the inconvenience. From now on I will definitely keep in mind your advice.

**Pull request merged**
