### PR TITLE
Allow to build without pulseaudio

### PR DESCRIPTION
**Pull request by bapt**
Instead of cherrypick OS that may or may not want pulseaudio, allow
to disable pulse by pass NO_PULSEAUDIO=1 to make

### CODE REVIEW

**Comment by uz2** [comment]
https://github.com/i3/i3status/pull/43 , https://github.com/i3/i3status/issues/101 , https://github.com/i3/i3status/issues/90

>@stapelberg sounds like a dictator.. with the same attitude as the gnome/systemd superheroes? i reached here tracing some arguments about people slagging off i3. my £0.02 re this issue is to remove the pulseaudio dependency.. period! not optional either!

i3status is complete joke right now. The second you dissagre with @stapelberg or @Airblader you'll be left in the dirt. They have no tolerance towards people trying to fix, improve or address issues, the second you do it they'll close the pull request or opened issue, pointing you that they holy grail software is so perfect that it doesn't need no ones help.

Compare how @ultrabug handles pull requests and how he communicates with his contributors.

@stapelberg and @Airblader have to focus their knowledge in i3 only, and **transfer** i3status to the community. Many talented people came and tried to improve this project was left dissapointed of those two authors attitudes.

Mister Torvalds had the same arogant attitude, many people pointed him this issue and he did take a note.

**Comment by Airblader** [comment]
@uz2 If you want to bring up such discussions, please do it on the mailing list. Pull requests like this are not the place for that. And either way, if you want anybody to take note I suggest you work on your tone for that.

This project is owned by @stapelberg and he can make decisions as he sees fit. If you want i3status to be something else there's virtually nothing stopping you from forking it. That's the beauty of open source. Coming into a project you're not contribution to and demanding to have your way and calling the maintainers dictators if we don't meet those demands isn't.

Please take this from the mailing list from here on out if you want to continue this conversation.

**Comment by bapt** [comment]
I have not seen previous PR of the same order, I understand @stapelberg position even if I do not necessary agree, if he doesn't want optional dependencies it is not a problem for me :)
Let's close that PR

**Comment by hasufell** [comment]
> to take note I suggest you work on your tone for that.

Please don't give us that crap. The second issue I see you pull out that big daddy card. If you treat contributors the way you do, you should expect some honest venting. And __you__ should be able to deal with it.

> there's virtually nothing stopping you from forking it. That's the beauty of open source.

That's not what open source is about. Not at all. You've misunderstood something here. Open source is about building a community and about collaboration, not just throwing out code and telling everyone to f* off and fork stuff as soon as there is minor disagreement. And this is by far not the first case I see this happening within the i3 "community". And no, this is not even about manpower or maintenance. There's literally not even a proper technical counter argument.

**Comment by stapelberg** [comment]
> Please don't give us that crap. The second issue I see you pull out that big daddy card. If you treat contributors the way you do, you should expect some honest venting. And you should be able to deal with it.

You’re way out of line. If you’d like to participate in the i3 project(s), please watch your tone.

I’ll close this discussion now, there’s nothing left to say.

**Pull request closed without merging**
