### PR TITLE
New "mail" module

### PR DESCRIPTION
**Pull request by czarkoff**
This request superceeds #45 and #48. This time it is a single module, that, unlike modules in those two previous requests, may be used several times in one i3status configuration without screwing the report. I tried to keep code documented, so that it should be easy to comprehend. I also tried to avoid wasting excessive amounts of memory and keep module safe from potential memory corruption issues (some people have really monstrous mailbox structure).

### CODE REVIEW

**Comment by czarkoff** [comment]
It seems I've finished tinkering with history, so this pull request can be reviewed now. I'll collapse all changes once you are ready to merge.

**Comment by stapelberg** [comment]
I see that you put in a lot of effort into this, but I’m starting to doubt whether having this module in i3status itself is a good idea. The fact that inventing a custom format strings seems to be necessary to cater to basic use-cases is not a good sign.

Maybe this functionality should instead go into a script in contrib/. That way, you could also use existing modules to parse maildir/mbox and we could avoid that code duplication. Also, you’d have more freedom with regards to config formats and how often you’d want to break them to support new use-cases.

The proposed module has grown to be one of the largest ones that i3status would have — the only other modules this big are battery and wifi, both of which have implementions for 3 different operating systems.

What do you think?

**Comment by czarkoff** [comment]
>The fact that inventing a custom format strings seems to be necessary to cater to basic use-cases is not a good sign.
> […]
> The proposed module has grown to be one of the largest ones that i3status would have

Custom format string is there because the module is supposed to present a lot of similar data pieces, so consistency in their presentation makes sense. This module could be reorganized to present single mailbox per *order* entry. This would allow dropping one level of singly-linked list and reducing the code by up to ¼ at expense of loosing prefixes and postfixes, forcing users to duplicate configuration entries and (probably) removing total message count. I guess almost ⅓ could be dropped with checking for names maildirs instead of huge maildir++. In other words, the complexity of this module may be reduced, if SLOC count and format strings syntax consistency are that important. That was not my goal though, and that's why the module is what it is.

FWIW if I was making *ethernet* and *wireless* modules, I would also make them one module and use similar format string with default format like "*N {%interface: %ip %essid signal}*". There is nothing inherently different about mail checking.

> Maybe this functionality should instead go into a script in contrib/.

As I gather, that makes sense for things that require custom update interval, which is definitely not the case here. Furthermore, this would lift limitation of periodic polling, so that the code (at least in my hands :smile:) will turn into a kqueue/epoll jungle. Even I am scared of this perspective.

On the other hand, doing the same in python would reduce this module to 100 SLOC or so, I guess. At least the checking part would be almost a one-liner. I am not sure about performance implications though – python script will likely bog down the whole setup under more or less heavy disk load, while this module performs well with 1 second interval even under heavy IO activity.

> That way, you could also use existing modules to parse maildir/mbox and we could avoid that code duplication.

That would be a nightmare. Most of what I see depends on glib, qt or some other monster lib I'd rather not venture into.

> What do you think?

My thoughs on the subject are expressed in commits above. I rely on mail notification in my status bar, and currently there is no way for me to get it without such module.

I could draft another version with less complexity (as described above), and a python script for `contrib/`, if you think that either is a good idea.

**Comment by stapelberg** [comment]
I agree with your points. I think adding a script in python, or whichever other high-level language you like that suits the task at hand, to the contrib/ folder would be a good idea. In case there is lots of user demand for the feature to be included with i3status itself, we can always revisit that with the new data and insights we get from providing a module in contrib/.

**Comment by czarkoff** [comment]
OK, closing this pull request for now. I'll open new pull request once python version is available.

**Pull request closed without merging**
