### PR TITLE
Fix NULL value on OpenBSD when there is no acpitz0

### PR DESCRIPTION
**Pull request by winks**
Using %degrees on OpenBSD resulted in garbage values if sysctl doesn't
know about any cpu temperature sensors.

### CODE REVIEW

**Comment by Airblader** [comment]
I think it'd be better to just first initialize the structure to some empty value and then have the logic run.

**Comment by su8** [comment]
```c
memset(&sensordev, 0, sizeof(struct sensordev));
memset(&sensor, 0, sizeof(struct sensor));
```

**Comment by su8** [comment]
You can also add

On line [124](https://github.com/winks/i3status/blob/93c82ffc25302fea1f12cfda5ac3b6bcdc2f189b/src/print_cpu_temperature.c#L124) you can add simple switch

```c
case SENSOR_TEMP:
  // do stuff
```

**Comment by Airblader** [comment]
I take that as you not pursuing to make changes to the PR, correct? Then I'll close it. Maybe someone else will want to pick it up. :-)

**Pull request closed without merging**
